### ISSUE TITLE
Upload ngx-event-calendar

### ISSUE THREAD

**Issue by celia-ms** [rhideg/ngx-table-manager#3]
Hi Richard H.,

The first forgive for my english (I'm spanish girl).

I have seen that you have several components implemented in npm and I liked them. I would like to know if you plan to upload the component "ngx-event-calendar" to github.

Thanks you!!

**Comment by rhideg** [comment]
Hey!

I'm really glad you liked them and uploading all of them to github is now in progress, check it in a few hours and it should be up.


Later on feel free to contribute or file issues/requests if you have any!

All the best,
Richard H.

________________________________

**Comment by celia-ms** [comment]
Hi again Richard H.

Thank you very much for the upload and offer to collaborate, these days I will try them and I will tell you but it is sure to be perfect.

All the best,

Chely
